"""One more column in Membership

Revision ID: 484bdfaf4a18
Revises: 4f30e22aa827
Create Date: 2025-11-07 02:23:29.124980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484bdfaf4a18'
down_revision: Union[str, Sequence[str], None] = '4f30e22aa827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_memberships', sa.Column('name', sa.String(), nullable=True))
    op.add_column('event_memberships', sa.Column('is_bot_user', sa.Boolean(), nullable=False))
    op.alter_column('event_memberships', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_memberships', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('event_memberships', 'is_bot_user')
    op.drop_column('event_memberships', 'name')
    # ### end Alembic commands ###
