"""Initial revision

Revision ID: 7809c69f7311
Revises: 
Create Date: 2025-11-03 03:45:49.774045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7809c69f7311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_events',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('place', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('members_limit', sa.Integer(), nullable=False),
    sa.Column('members_left', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.Enum('FRENCH_CLUB', 'TABLE_GAMES', 'BUISNESS_MEETS', 'WOMEN_MEETS', 'INITIATIVE', name='eventtype', create_type=False), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=32), nullable=False),
    sa.Column('register_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('has_private', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('event_memberships',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_ad', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_memeber', sa.Boolean(), nullable=False),
    sa.Column('is_come', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['member_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiatives',
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('place', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initiatives')
    op.drop_table('event_memberships')
    op.drop_table('users')
    op.drop_table('member_events')
    # ### end Alembic commands ###
    op.execute('DROP TYPE IF EXISTS eventtype')
