"""Holder field in Event

Revision ID: a5994dfecd52
Revises: f9da1ce70efa
Create Date: 2025-11-07 10:41:40.879768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5994dfecd52'
down_revision: Union[str, Sequence[str], None] = 'f9da1ce70efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_events', sa.Column('holder', sa.String(length=100), nullable=False, server_default="Не указан"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_events', 'holder')
    # ### end Alembic commands ###
