"""New fields in user model

Revision ID: ba5b9f2bd6d1
Revises: a5994dfecd52
Create Date: 2025-11-08 10:58:07.119775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5b9f2bd6d1'
down_revision: Union[str, Sequence[str], None] = 'a5994dfecd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False, server_default="Не указано"))
    op.add_column('users', sa.Column('alias', sa.String(length=100), nullable=False, server_default="Анонимный пользователь"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
