"""On deletes

Revision ID: f9da1ce70efa
Revises: 62d44353369f
Create Date: 2025-11-07 03:07:44.256054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9da1ce70efa'
down_revision: Union[str, Sequence[str], None] = '62d44353369f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_memberships_event_id_fkey'), 'event_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'event_memberships', 'member_events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_memberships', type_='foreignkey')
    op.create_foreign_key(op.f('event_memberships_event_id_fkey'), 'event_memberships', 'member_events', ['event_id'], ['id'])
    # ### end Alembic commands ###
